### PR TITLE
All changes implemented, current run happening. Link to wandb  run in comments. 

### PR DESCRIPTION
**Pull request by krish240574**
https://wandb.ai/laion/diffusion-prior/runs/33s12asp?workspace=user-krish240574

### CODE REVIEW

**Comment by rom1504** [comment]
@lucidrains

**Comment by lucidrains** [comment]
🙏 🙇

**Comment by krish240574** [comment]
Thanks !

**Comment by rom1504** [comment]
https://github.com/lucidrains/DALLE2-pytorch/issues/23#issuecomment-1114320667 and here's the first checkpoint
let's see what it's worth!

**Pull request merged**
