### PR TITLE
Add another upsample technique

### PR DESCRIPTION
**Pull request by MalumaDev**
Add another upsample technique: PixelShuffle (https://arxiv.org/pdf/1609.05158v2.pdf).
This technique should help to avoid the emergence of checkerboard artifacts.

### CODE REVIEW

**Comment by lucidrains** [comment]
@MalumaDev thank you 🙏 ! does this fix the upsampler issues for you?

**Comment by MalumaDev** [comment]
I have yet to test it for full training, but I have used it in other works. I have only one GPU and the test will require some times.

**Comment by lucidrains** [comment]
Cool, I'll test it next week trying to debug the artifacts we see in the other issue

**Comment by lucidrains** [comment]
@marunine if Katherine is doing it, it is probably a good idea haha https://github.com/lucidrains/DALLE2-pytorch/commit/bdd62c24b367847abeb1bbf5f2b7b77311ed84fb

**Comment by marunine** [comment]
I remembered reading about it from one of the Adam authors before - comes from the GLOW paper.

The good news is that I'm no longer seeing checkerboarding on the Imagen repo with the zero initialization + pixel shuffle at least. Haven't tried out the zero initialization alone, but no checkerboarding on a fresh run even in the early steps is great.

**Comment by lucidrains** [comment]
@marunine @MalumaDev  thank you both!

**Pull request closed without merging**
