### PR TITLE
Added some documentation for the diffusion prior in README.md

### PR DESCRIPTION
**Pull request by krish240574**
This PR is in response to https://github.com/lucidrains/DALLE2-pytorch/issues/58 
K

### CODE REVIEW

**Comment by lucidrains** [comment]
@krish240574 looks good! but it seems like you reverted some changes i made to the readme

i think there is some issue with how you merged?

**Comment by krish240574** [comment]
yes, I probably screwed up the merge - should I undo my changes?

**Comment by lucidrains** [comment]
@krish240574 yup! you should definitely go through the pain of this :smiley:  nobody likes merges in industry (including me) but it is a necessary skill! :laughing:

**Comment by krish240574** [comment]
I'm fixing the merge, no worries. I'll revert in a bit. AArgh.

**Comment by lucidrains** [comment]
@krish240574 there's a nice GUI tool out there, called https://www.sublimemerge.com/ may help you

**Comment by krish240574** [comment]
@lucidrains, thank you, I appreciate the infinite patience !

**Pull request merged**
